# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"\x1d\n\x0fUserInfoRequest\x12\n\n\x02id\x18\x01 \x01(\t\"T\n\rUserInfoReply\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\x12\r\n\x05roles\x18\x05 \x01(\t2?\n\x04User\x12\x37\n\x07GetInfo\x12\x15.user.UserInfoRequest\x1a\x13.user.UserInfoReply\"\x00\x62\x06proto3')



_USERINFOREQUEST = DESCRIPTOR.message_types_by_name['UserInfoRequest']
_USERINFOREPLY = DESCRIPTOR.message_types_by_name['UserInfoReply']
UserInfoRequest = _reflection.GeneratedProtocolMessageType('UserInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERINFOREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.UserInfoRequest)
  })
_sym_db.RegisterMessage(UserInfoRequest)

UserInfoReply = _reflection.GeneratedProtocolMessageType('UserInfoReply', (_message.Message,), {
  'DESCRIPTOR' : _USERINFOREPLY,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.UserInfoReply)
  })
_sym_db.RegisterMessage(UserInfoReply)

_USER = DESCRIPTOR.services_by_name['User']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERINFOREQUEST._serialized_start=20
  _USERINFOREQUEST._serialized_end=49
  _USERINFOREPLY._serialized_start=51
  _USERINFOREPLY._serialized_end=135
  _USER._serialized_start=137
  _USER._serialized_end=200
# @@protoc_insertion_point(module_scope)
