"""create_table_totp_device

Revision ID: 85640f5bdf20
Revises: c795938d63e6
Create Date: 2022-04-30 19:49:49.421496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85640f5bdf20'
down_revision = 'c795938d63e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('totp_device',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('digits', sa.Integer(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    schema='auth'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('totp_device', schema='auth')
    # ### end Alembic commands ###
