version: '2.2'
services:
    logstash:
        image: docker.elastic.co/logstash/logstash:7.10.2
        depends_on:
          - elasticsearch
        environment:
          XPACK_MONITORING_ENABLED: "false"
          ES_HOST: "elasticsearch:9200"
        ports:
          - "5044:5044/udp"
        volumes:
          - ./deploy/logstash.conf:/config/logstash.conf:ro
        command: logstash -f /config/logstash.conf

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
      environment:
        discovery.type: single-node
      ports:
        - 9200:9200
      volumes:
        - /tmp/esdata:/tmp/elasticsearch/data

    kibana:
        image: docker.elastic.co/kibana/kibana:7.10.2
        ports:
          - "5601:5601"
        depends_on:
          - elasticsearch